"""Initial migration

Revision ID: edfdb4f1e721
Revises: 
Create Date: 2026-04-09 11:40:52.093383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfdb4f1e721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_data_id'), 'traffic_data', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_data_location_id'), 'traffic_data', ['location_id'], unique=False)
    op.create_index(op.f('ix_traffic_data_timestamp'), 'traffic_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_data_timestamp'), table_name='traffic_data')
    op.drop_index(op.f('ix_traffic_data_location_id'), table_name='traffic_data')
    op.drop_index(op.f('ix_traffic_data_id'), table_name='traffic_data')
    op.drop_table('traffic_data')
    # ### end Alembic commands ###
